Entities and Relations
kbsaxena/Shopping pull request #4
Opened 2020-02-04 10:43 UTC by pradeeprach

2020-02-04 13:26 UTC, kbsaxena requested changes

2020-02-04 13:26 UTC, kbsaxena commented on src/main/java/com/shopping/entities/Account.java
> +	private ShoppingCart shoppingCart;
Add relationship with Customer

2020-02-04 13:26 UTC, kbsaxena commented on src/main/java/com/shopping/entities/Customer.java
> +	@OneToMany
Add Bidirectional relationship to Account

2020-02-04 13:26 UTC, kbsaxena commented on src/main/java/com/shopping/entities/Customer.java
> +	private List<Phone> phoneNumbers;
This should be a Set.All phone numbers will be unique

2020-02-04 13:26 UTC, kbsaxena commented on src/main/java/com/shopping/entities/Phone.java
> +	private String mobileNumber;
Add getter and setters

2020-02-04 13:26 UTC, kbsaxena commented on src/main/java/com/shopping/entities/Phone.java
> +}
Add Bidirectional relationship to Customer

2020-02-04 13:26 UTC, kbsaxena commented on src/main/java/com/shopping/entities/ShoppingCart.java
> +	private TreeSet<LineItem> lineItems;
we need to initialize here only with new object to eradicate null pointers

2020-02-04 13:26 UTC, kbsaxena commented on src/main/java/com/shopping/entities/User.java
> +	@OneToOne(optional=true)
remove optional parameter

2020-02-04 15:17 UTC, pradeeprach commented on src/main/java/com/shopping/entities/User.java
> +	@OneToOne(optional=true)
Please verify the image. There it is specified as either 0 or 1. That is the reason I marked it optional.

2020-02-05 07:35 UTC, kbsaxena commented on src/main/java/com/shopping/entities/User.java
> +	@OneToOne(optional=true)
Ok

2020-02-05 10:33 UTC, closed without merging